name: 'CI'

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened, synchronize]
  schedule:
    - cron: '0 1 * * 6'

jobs:
  pre-commit:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
          pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pytest
      - name: Run dotenv_to_csv.py unit tests
        run: pytest test_dotenv_to_csv.py -v
        working-directory: test

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        idf_ver: ["release-v5.5", "release-v6.0"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build example
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ matrix.idf_ver }}
          target: esp32
          path: examples/nvs-dotenv-example

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build and test in QEMU
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: latest
          target: esp32
          path: examples/nvs-dotenv-example
          command: pip install pytest-embedded pytest-embedded-idf pytest-embedded-qemu && idf.py build && pytest
